### ISSUE TITLE
NeoForge 1.20.4 Mod does not load / initialize

### ISSUE THREAD

**Issue by MSandro** [D0CTOR-ZED/GenMogrify-docs#1]
the mod is not showing up in the mod list.

**Comment by D0CTOR-ZED** [comment]
> the mod is not showing up in the mod list.

Can you confirm you are using GenMogrify-neo-1.20.4-0.1.0.jar.  Specifically, the -neo- and 1.20.4 parts.

**Comment by D0CTOR-ZED** [comment]
Never mind the confirmation request.  I am able to reproduce the issue and should be able to get a new version out tomorrow.

**Comment by D0CTOR-ZED** [comment]
Fixed version reference issue. Uploaded new version.... pending Curseforge approval.  If you continue to experience this issue, please reopen this issue.  https://www.curseforge.com/minecraft/mc-mods/genmogrify/files/all
